repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: double-quote-string-fixer
-   repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.12.0]
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    - id: black
      language_version: python3.8
# -   repo: meta
#     hooks:
#     -   id: check-hooks-apply
#     -   id: check-useless-excludes
